// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package authors1

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Authors2 struct {
	ID   int64
	Name string
	Bio  pgtype.Text
}
